package com.coblax.examlock.ui.admin

import android.graphics.Bitmap
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Column
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.asAndroidBitmap
import androidx.compose.ui.test.SemanticsNodeInteraction
import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.assertIsOff
import androidx.compose.ui.test.assertIsOn
import androidx.compose.ui.test.captureToImage
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onNodeWithTag
import androidx.compose.ui.test.onNodeWithText
import androidx.compose.ui.test.onRoot
import androidx.compose.ui.test.performClick
import androidx.compose.ui.test.performScrollTo
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.coblax.examlock.ExamQrCodec
import com.coblax.examlock.ExamQrSecurityBypass
import com.coblax.examlock.i18n.LocalUiLanguage
import com.coblax.examlock.model.CustomQrAdminTab
import com.coblax.examlock.model.ThemeMode
import com.coblax.examlock.model.UiLanguage
import com.coblax.examlock.ui.preparation.PreparationCategory
import com.coblax.examlock.ui.preparation.PreparationCategoryStatus
import com.coblax.examlock.ui.preparation.PreparationOverview
import com.coblax.examlock.ui.preparation.PreparationStartBar
import com.coblax.examlock.ui.preparation.PreparationStatusCard
import com.coblax.examlock.ui.theme.AppColors
import com.coblax.examlock.ui.theme.COBLAXEXAMLOCKTheme
import com.coblax.examlock.viewmodel.CustomQrDraftState
import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class CustomQrBypassUiTest {
    @get:Rule
    val composeRule = createComposeRule()

    private var draft by mutableStateOf(
        CustomQrDraftState(examUrl = "https://ujian.example.com", examName = "UTS Matematika")
    )
    private var generated by mutableStateOf<String?>(null)

    private fun show(themeMode: ThemeMode = ThemeMode.Light) {
        composeRule.setContent {
            CompositionLocalProvider(LocalUiLanguage provides UiLanguage.Indonesian) {
                COBLAXEXAMLOCKTheme(themeMode = themeMode) {
                    CustomQrAdminScreen(
                        showSaveToDirectLinkOption = true,
                        onBack = {},
                        selectedTabName = CustomQrAdminTab.Generate.name,
                        draft = draft,
                        onDraftChange = { draft = it },
                        generatedQrPayload = generated,
                        onGeneratedQrPayloadChange = { generated = it }
                    )
                }
            }
        }
    }

    private fun row(bypass: ExamQrSecurityBypass): SemanticsNodeInteraction =
        composeRule.onNodeWithTag(CustomQrBypassUiTestTags.RowPrefix + bypass.key).performScrollTo()

    @Test
    fun chosenBypassesAreListedAndTravelInTheGeneratedQr() {
        show()
        composeRule.onNodeWithText("Tidak ada. Semua pemeriksaan berlaku.").assertIsDisplayed()

        composeRule.onNodeWithTag(CustomQrBypassUiTestTags.EditAction).performClick()
        row(ExamQrSecurityBypass.Bluetooth).assertIsOff().performClick().assertIsOn()
        row(ExamQrSecurityBypass.Geofence).performClick().assertIsOn()
        composeRule.onNodeWithText("2 dipilih").assertIsDisplayed()
        composeRule.onNodeWithTag(CustomQrBypassUiTestTags.DoneAction).performClick()

        composeRule.onNodeWithText("Cek Bluetooth, Geofence").assertIsDisplayed()
        composeRule.runOnIdle {
            assertEquals(
                setOf(ExamQrSecurityBypass.Bluetooth, ExamQrSecurityBypass.Geofence),
                draft.securityBypasses
            )
        }

        composeRule.onNodeWithText("Generate QR").performClick()
        composeRule.waitUntil(timeoutMillis = 10_000) { generated != null }
        assertEquals(draft.securityBypasses, ExamQrCodec.decrypt(generated!!).securityBypasses)
    }

    /** Changing what the QR relaxes must never leave an older QR on screen to hand out. */
    @Test
    fun changingTheBypassesClearsTheGeneratedQr() {
        generated = "CBXEL2:stale"
        show()
        composeRule.onNodeWithTag(CustomQrBypassUiTestTags.EditAction).performClick()
        row(ExamQrSecurityBypass.Vpn).performClick()
        composeRule.runOnIdle { assertNull(generated) }

        composeRule.onNodeWithTag(CustomQrBypassUiTestTags.ClearAction).performScrollTo().performClick()
        composeRule.runOnIdle { assertEquals(emptySet<ExamQrSecurityBypass>(), draft.securityBypasses) }
    }

    @Test
    fun pickerAndSummaryRenderInDarkMode() {
        draft = draft.copy(
            securityBypasses = setOf(
                ExamQrSecurityBypass.ScreenPinning,
                ExamQrSecurityBypass.Bluetooth,
                ExamQrSecurityBypass.DeviceTime
            )
        )
        show(ThemeMode.Dark)
        composeRule.onNodeWithTag(CustomQrBypassUiTestTags.Section).assertIsDisplayed()
        save(composeRule.onRoot(), "custom-qr-bypass-section.png")

        composeRule.onNodeWithTag(CustomQrBypassUiTestTags.EditAction).performClick()
        save(composeRule.onNodeWithTag(CustomQrBypassUiTestTags.Picker), "custom-qr-bypass-picker.png")
    }

    /** Reopening Custom QR continues the last draft and offers the one way to start over. */
    @Test
    fun resumedDraftOffersStartingOver() {
        var startedOver = false
        composeRule.setContent {
            CompositionLocalProvider(LocalUiLanguage provides UiLanguage.Indonesian) {
                COBLAXEXAMLOCKTheme(themeMode = ThemeMode.Dark) {
                    CustomQrAdminScreen(
                        showSaveToDirectLinkOption = false,
                        onBack = {},
                        draft = draft,
                        onDraftChange = { draft = it },
                        draftResumed = true,
                        onStartNewDraft = { startedOver = true }
                    )
                }
            }
        }
        composeRule.onNodeWithText("Melanjutkan draf terakhir.").assertIsDisplayed()
        save(composeRule.onRoot(), "custom-qr-resumed-draft.png")

        composeRule.onNodeWithTag(CustomQrStartNewDraftTestTag).performClick()
        composeRule.runOnIdle { assertEquals(true, startedOver) }
    }

    /** What the student and proctor see before starting an exam from a bypass QR. */
    @Test
    fun preparationNamesWhatTheQrTurnsOff() {
        composeRule.setContent {
            CompositionLocalProvider(LocalUiLanguage provides UiLanguage.Indonesian) {
                COBLAXEXAMLOCKTheme(themeMode = ThemeMode.Dark) {
                    val categories = PreparationCategory.entries.map { category ->
                        PreparationCategoryStatus(category = category, issues = emptyList(), actions = emptyList())
                    }
                    val overview = PreparationOverview(
                        categories = categories,
                        attention = emptyList(),
                        canStartExam = true,
                        scanPending = false
                    )
                    Column(Modifier.background(AppColors.current.background)) {
                        PreparationStatusCard(
                            overview = overview,
                            hasBypassIndicators = true,
                            qrBypassTitles = listOf("Cek Bluetooth", "Geofence")
                        )
                        PreparationStartBar(
                            overview = overview,
                            isStartingExam = false,
                            webViewSessionResetInFlight = false,
                            hasBypassIndicators = true,
                            bypassFromQrOnly = true,
                            onStartExam = {}
                        )
                    }
                }
            }
        }
        composeRule.onNodeWithText("QR ujian melonggarkan: Cek Bluetooth, Geofence. Semua tetap dicatat.")
            .assertIsDisplayed()
        composeRule.onNodeWithText("Bypass dari QR ujian aktif.").assertIsDisplayed()
        save(composeRule.onRoot(), "preparation-qr-bypass.png")
    }

    private fun save(node: SemanticsNodeInteraction, name: String) {
        composeRule.waitForIdle()
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        File(context.getExternalFilesDir(null), name).outputStream().use {
            node.captureToImage().asAndroidBitmap().compress(Bitmap.CompressFormat.PNG, 100, it)
        }
    }
}
