package com.example.coblaxexamlock.config
internal const val SecretTapWindowMs = 2000L
internal const val ClipboardListenerWarmupIgnoreMillis = 1200L
internal const val ClipboardSettleWindowMillis = 450L
internal const val ClipboardResumeSettleWindowMillis = 700L
internal const val ClipboardResumeConfirmWindowMillis = 300L
internal const val AlarmAcknowledgeDedupWindowMillis = 3000L
internal const val AppSwitchSuppressionWindowMillis = 12000L
internal const val OverlayFocusLossConfirmWindowMillis = 350L
internal const val OfflineTooLongWarningThresholdMillis = 30000L
internal const val NetworkUnstableFlipThreshold = 3
internal const val NetworkUnstableWindowMillis = 120000L
internal const val NetworkUnstableRecoveryQuietPeriodMillis = 60000L
internal const val MaxNetworkTimelineEntries = 20
internal const val LowMaxNetworkTimelineEntries = 12
internal const val UltraMaxNetworkTimelineEntries = 6
internal const val GeofenceRuntimeRecheckIntervalMillis = 30000L
internal const val GeofenceCurrentLocationTimeoutMillis = 3500L
internal const val MaxDiagnosticActionLogEntries = 20
internal const val TelegramMessageChunkLimit = 3400

// Telegram retry + offline queue
internal const val TelegramRetryMaxAttempts = 3
internal const val TelegramRetryBaseDelayMs = 1000L
internal const val TelegramRetryMultiplier = 3.0
internal const val TelegramRetryJitterFraction = 0.2
internal const val TelegramRateLimitMaxTokens = 5
internal const val TelegramRateLimitRefillPeriodMs = 10_000L
internal const val TelegramOfflineQueueMaxSize = 50
